<?php
$countries = [
    "USA",
    "UK",
    "Nigeria",
    "India",
    "Australia",
    "Canada",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Brazil",
    "Mexico",
    "China",
    "Japan",
    "South Korea",
    "Russia",
    "South Africa",
    "Argentina",
    "Colombia",
    "Vietnam",
    "Thailand",
    "Turkey",
    "Saudi Arabia",
    "Egypt",
    "Ghana",
    "Philippines",
    "Pakistan",
    "Indonesia",
    "Malaysia",
    "Singapore",
    "New Zealand",
    "Norway",
    "Sweden",
    "Finland",
    "Denmark",
    "Iceland",
    "Ireland",
    "Portugal"
];
